Repository Qoraiche/laravel-mail-editor, pull requests merged in 2020-10, with the labels that each got.

#115 Fix compliance with psr-4 autoloading standard.
  src/Command/VendorPublishCommand.php
Labels: Good Issue, V2, V3

#118 Fix compliance with psr-4 autoloading standard.
  src/Command/VendorPublishCommand.php
  src/MailEclipse.php
Labels: V2

#121 Fix Factory not resolving [laravel 8]
  src/MailEclipse.php
Labels: WIP, laravel 8
